export const dummytest = {
  question_id: "",
  question_text:
    "Bull A B C D Birth Weight Sire 1 Sire 2 Sire 3 EPD 6.6 0.1 0.0 -5.9 Locus 1 Offspring AA Who is the sire? AA Aa Aa Acc. 0.75 0.82 0.89 0.87 What do we estimate would be the weaning weight for Bull C's calf if the breed average is 595 lbs? What was the birth weight of Bull A? Locus 2 Bb BB Bb bb Weaning Weight EPD Acc. EPD Acc. 31.3 0.75 39.5 0.68 14.6 0.83 24.6 0.80 0.3 0.89 11.1 0.88 -3.8 0.87 -14.4 0.86 Locus 3 Locus 4 Cc dd CC Cc \u0441\u0441 Yearling Weight DD Dd dd Locus 5 Ee EE ee Ee Locus 6 FF Ff ff FF EPD -5.6 6.0 18.9 10.3 Locus 7 Gg Gg GG Milk Acc. 0.58 0.73 0.87 0.85",
  answer_id: "9a98aff7-197e-4403-822a-c67f40ea50c3",
  answer_steps:
    '[{"sequence":"0","header":"Step 1: Introduction","text":"<p>In this scenario, we are presented with data related to bulls and their respective genetic traits. We also have information on the offspring and potential sires. The goal is to analyze the data and make certain estimations and identifications based on the given information. By examining the provided data, we can draw conclusions about various factors such as birth weight, weaning weight, and determining the sire of the offspring. </p>"},{"sequence":"1","header":"Step 2: Estimating the weaning weight, birth weight and Sire based on the given data","text":"<p><strong>Answer 1:</strong> To estimate the weaning weight for Bull C\'s calf if the breed average is 595 lbs, we need to consider the EPD (Expected Progeny Difference) for weaning weight. Bull C\'s EPD for weaning weight is 0.3.</p><p>The estimated weaning weight can be calculated by adding the breed average (595 lbs) to Bull C\'s weaning weight EPD (0.3): Estimated Weaning Weight = Breed Average + EPD Estimated Weaning Weight = 595 lbs + 0.3 Estimated Weaning Weight = 595.3 lbs</p><p><strong>Therefore, the estimated weaning weight for Bull C\'s calf would be approximately 595.3 lbs.</strong></p><p><strong>Answer 2:</strong> The birth weight of Bull A is given as <strong>6.6</strong> with an accuracy of 0.75. This indicates that the estimated birth weight is 6.6 lbs, and the accuracy value represents the reliability of the estimation.</p><p><strong>Answer 3:</strong> To determine the sire based on the loci provided, we need to compare the alleles of the offspring with those of the potential sires. Looking at the loci and alleles:</p><p>Offspring: AA, Bb, Cc, dd, Ee, FF, Gg </p><p>Sire 1: AA, BB, CC, DD, EE, Ff, Gg </p><p>Sire 2: Aa, Bb, Cc, Dd, ee, ff, GG </p><p>Sire 3: Aa, bb, cc, dd, Ee, FF, gg</p><p>By comparing the offspring alleles with the potential sires, we can determine that Sire 3 is the sire because it shares the most matching alleles with the offspring. The matching alleles are Aa, cc, dd, Ee, FF, and gg.</p><p><strong>Therefore, Sire 3 is the sire based on the matching alleles at the provided loci.</strong></p>"},{"sequence":"2","header":"Solution","text":"<p>1. The estimated weaning weight for Bull C\'s calf would be approximately 595.3 lbs.</p><p>2. The birth weight of Bull A is 6.6 lbs.</p><p>3. Sire 3 is the likely sire based on the matching alleles at the provided loci.</p>"}]',
  subject: "biology",
  plan: "I can certainly help you with that! Here are brief summaries of each step:\nStep 1: Introduction\n    - We have data on bulls and their offspring, and we need to analyze the information to make estimations and identifications.\nStep 2: Estimating the weaning weight, birth weight, and Sire\n    - We use EPDs to estimate the weaning weight for Bull C's calf.\n    - We calculate the estimated weaning weight by adding the breed average to Bull C's weaning weight EPD.\n    - We determine the birth weight of Bull A by analyzing the accuracy of the estimation.\n    - We use the loci and alleles of the offspring to determine the sire based on the matching alleles.\nStep 3: Conclusion\n    - We have estimated the weaning weight for Bull C's calf, determined the birth weight of Bull A, and identified the sire of the offspring based on the loci and alleles.",
};
